### ISSUE TITLE
Spotify Premium Issue

### ISSUE THREAD

**Issue by KittyCatCrunchie** [apkmody/apkmody.com#20]
I was trying to upgrade from the Premium Mod from Oct 2021 to the most recent one but after installing it, all login attempts are unsuccessful. I reinstalled the old one and it still works perfectly. 
Image subtitle: Picture of Spotify pop-up with the text "Une erreur s'est produite. Réessayez." which means "An error has occurred. Try again."
![Screenshot_20220125-112202](https://user-images.githubusercontent.com/62380752/150950153-cd951d93-52d1-4b5b-985f-82c4216a033e.png)

**Comment by anhphammody** [comment]
Please try again with the latest version: https://apkmody.com/apps/spotify
