### ISSUE TITLE
Spotify premium mod is not working anymore.

### ISSUE THREAD

**Issue by MohamedLaraj** [apkmody/apkmody.com#7]
Spotify premium mod started working like the regular version, no unlimited skips, no shuffle, etc...
Pls make a new version asap.

**Comment by anhphammody** [comment]
Please try again with the latest version, you can download it here https://apkmody.com/apps/spotify

**Comment by modded-1-com** [comment]
You can retry the latest, fastest updated and revised version on the Android platform here. https://modded-1.com/apps/music-audio/spotify
